#!/usr/bin/env sh

set -e

# Local Wrapper Properties File
DIR="$(cd -- "$(dirname "$0")"; pwd -P)"
WRAPPER_FILE="$DIR/.corretto/wrapper.properties"

# Script Arguments override wrapper file if present
CORRETTO_JDK_VERSION="${1:-"$(grep 'version' $WRAPPER_FILE | cut -f 2 -d '=' | tr -d ' ' | tr -d '\r\n')"}"
CORRETTO_JDK_DIST="${2:-"$(grep 'dist' $WRAPPER_FILE | cut -f 2 -d '=' | tr -d ' ' | tr -d '\r\n')"}"

# Script Variables
OS="$(echo "$CORRETTO_JDK_DIST" | cut -f 1 -d '-' | tr -d ' ' | tr -d '\r\n')"
WRAPPER_DIR="$HOME/.corretto/wrapper"
DIST_DIR="$WRAPPER_DIR/dist"
CORRETTO_JDK_DIST_FULL="amazon-corretto-$CORRETTO_JDK_VERSION-$CORRETTO_JDK_DIST"
CORRETTO_JDK_HOME="$WRAPPER_DIR/$CORRETTO_JDK_DIST_FULL"
CORRETTO_DOWNLOAD_FILE="$CORRETTO_JDK_DIST_FULL.tar.gz"
CORRETTO_DOWNLOAD_URL="https://corretto.aws/downloads/resources/$CORRETTO_JDK_VERSION/$CORRETTO_DOWNLOAD_FILE"

# Special macosx directory structure
if [ "macosx" = "$OS" ];
then
  CORRETTO_JDK_HOME="$CORRETTO_JDK_HOME/Contents/Home"
fi

# Check to see if the Corretto JDK home already exists
if [ ! -d "$CORRETTO_JDK_HOME" ];
then

  # Make directory if necessary
  mkdir -p "$DIST_DIR"

  # Download JDK
  >&2 echo "Downloading Corretto JDK [$CORRETTO_JDK_VERSION]..."
  if ! DL_HTTP_CODE=$(curl -sL -o "$DIST_DIR/$CORRETTO_DOWNLOAD_FILE" -w "%{http_code}" "$CORRETTO_DOWNLOAD_URL");
  then
    >&2 echo "Error downloading Corretto JDK, please confirm version [$CORRETTO_JDK_VERSION]"
    exit 1
  fi
  if echo "$DL_HTTP_CODE" | grep -q '^4.*'; # HTTP 4xx error
  then
    >&2 echo "Error downloading Corretto JDK (HTTP $DL_HTTP_CODE), please confirm version [$CORRETTO_JDK_VERSION]"
    exit 1
  fi

  # Extract
  >&2 echo "Extracting Corretto JDK [$CORRETTO_JDK_VERSION]..."
  if ! tar -xf "$DIST_DIR/$CORRETTO_DOWNLOAD_FILE" -C "$WRAPPER_DIR";
  then
    >&2 echo "Error extracting Corretto JDK, please submit a bug report: https://github.com/brianwyka/corretto-jdk-wrapper/issues/new/choose"
  fi

  # Handle macosx rename
  if [ "macosx" = "$OS" ];
  then
    # Derive the base JDK version and then rename the directory to full version
    # i.e. - amazon-corretto-17.jdk > amazon-corretto-17.0.4.9.1-linux-x64
    # This is done to be able to store multiple sub-versions at the same time
    CORRETTO_JDK_BASE_VERSION="$( echo "$CORRETTO_JDK_VERSION" | cut -f 1 -d '.')"
    mv "$WRAPPER_DIR/amazon-corretto-$CORRETTO_JDK_BASE_VERSION.jdk" "$WRAPPER_DIR/$CORRETTO_JDK_DIST_FULL"
  fi

  >&2 echo "Successfully installed Corretto JDK [$CORRETTO_JDK_VERSION]"

fi

# Print out Corretto JDK Home
echo "$CORRETTO_JDK_HOME"
